name: Deployment to S3
on:
  push:
    branches: [main]

# Cancel previous running workflows to avoid redundant builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout to last commit
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'npm'
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # use AWS CLI to sync the build folder to the S3 bucket
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::635082913709:role/github-provider-role

      - name: Deploy to S3
        run: |
          npm run build && aws s3 sync build/ s3://hunky-frontend --delete
    